name: Deploy Static Website

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::932103793095:role/GitHubActionsS3Deploy
          aws-region: ap-south-2

      - name: Deploy website to S3
        run: |
          aws s3 sync . s3://kaif-aws-static-website-2026 \
            --exclude ".git/*" \
            --exclude ".github/*"